# Generated by Django 3.2 on 2021-04-22 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('gender', models.CharField(choices=[('M', 'Mr'), ('W', 'Mme')], default='M', max_length=1, verbose_name='gender')),
                ('name', models.CharField(max_length=255, verbose_name='fullname')),
                ('private_key', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='private api key')),
                ('user_uuid', models.UUIDField(blank=True, default=None, editable=False, null=True, verbose_name='private id')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
        ),
    ]
