# Generated by Django 3.2 on 2021-05-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210429_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Mr'), ('W', 'Ms.'), ('U', 'Undefined')], default='M', max_length=1, verbose_name='gender'),
        ),
    ]
