FROM python:3.7.10-stretch

# Update with new repo
RUN apt-get update

# Install software
RUN apt-get install -y git

COPY requirements.txt ./requirements.txt
RUN pip install -r /requirements.txt

WORKDIR /usr/src/app

EXPOSE 8061

# different settings from local dev
ENV DJANGO_SETTINGS_MODULE=plan_heure.settings.production

CMD [ "gunicorn", "plan_heure.wsgi", "-b", "0.0.0.0:8061" ]