---
version: '3'

services:

  plan_heure_nginx:
    container_name: plan_heure_nginx
    restart: always
    image: nginx
    depends_on:
      - plan_heure_web
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - '8060:80'
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=plan_heure_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:plan_heure.com,www.plan_heure.com'
      - 'traefik.docker.network=traefik'

  plan_heure_web:
    container_name: plan_heure_web
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.staging
    depends_on:
      - plan_heure_db
    links:
      - plan_heure_db:database
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./:/usr/src/app
    networks:
      - traefik

  plan_heure_db:
    container_name: plan_heure_db
    restart: always
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: proxy
...
