# Generated by Django 3.2 on 2021-04-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_reservation_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='users.user',
                verbose_name='creator'
            ),
            preserve_default=False,
        ),
    ]
