# Generated by Django 3.2 on 2021-04-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210429_1525'),
        ('reservations', '0003_reservation_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='resource',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reservation',
                to='resources.resource',
                verbose_name='reservation'
            ),
        ),
    ]
