# Generated by Django 3.2 on 2021-05-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210429_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.SmallIntegerField(verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='location',
            name='label',
            field=models.CharField(max_length=64, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='capacity',
            field=models.PositiveSmallIntegerField(verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='label',
            field=models.CharField(max_length=64, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource', to='resources.location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='label',
            field=models.CharField(max_length=64, verbose_name='label'),
        ),
    ]
